//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opportunity.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Badania
    {
        public int id { get; set; }
        public string numer { get; set; }
        public int id_pracownika { get; set; }
        public Nullable<System.DateTime> data_wydania { get; set; }
        public Nullable<System.DateTime> data_waznosci { get; set; }
        public string uwagi { get; set; }
        public string path { get; set; }
        public string uzytkownik { get; set; }
        public System.DateTime last_update { get; set; }
        public bool nieaktywne { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
