//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opportunity.Model.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpportunityEntities : DbContext
    {
        public OpportunityEntities()
            : base("name=OpportunityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Badania> Badania { get; set; }
        public virtual DbSet<Oswiadczenia> Oswiadczenia { get; set; }
        public virtual DbSet<Paszporty> Paszporty { get; set; }
        public virtual DbSet<Potwierdzenia> Potwierdzenia { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Przyjecia> Przyjecia { get; set; }
        public virtual DbSet<Slownik_typy_towarow> Slownik_typy_towarow { get; set; }
        public virtual DbSet<SzkoleniaBHP> SzkoleniaBHP { get; set; }
        public virtual DbSet<Towary> Towary { get; set; }
        public virtual DbSet<Wizy> Wizy { get; set; }
        public virtual DbSet<Wycofania> Wycofania { get; set; }
        public virtual DbSet<Wydania> Wydania { get; set; }
        public virtual DbSet<Zaproszenia> Zaproszenia { get; set; }
        public virtual DbSet<Zezwolenia> Zezwolenia { get; set; }
        public virtual DbSet<v_wydania> v_wydania { get; set; }
        public virtual DbSet<Slownik_marki> Slownik_marki { get; set; }
        public virtual DbSet<Zatrudnienia> Zatrudnienia { get; set; }
    }
}
