//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opportunity.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownicy()
        {
            this.Badania = new HashSet<Badania>();
            this.Oswiadczenia = new HashSet<Oswiadczenia>();
            this.Paszporty = new HashSet<Paszporty>();
            this.SzkoleniaBHP = new HashSet<SzkoleniaBHP>();
            this.Wizy = new HashSet<Wizy>();
            this.Wydania = new HashSet<Wydania>();
            this.Wydania1 = new HashSet<Wydania>();
            this.Zaproszenia = new HashSet<Zaproszenia>();
            this.Zezwolenia = new HashSet<Zezwolenia>();
            this.Zatrudnienia = new HashSet<Zatrudnienia>();
        }
    
        public int id { get; set; }
        public string numer { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public Nullable<System.DateTime> data_urodzenia { get; set; }
        public bool brygadzista { get; set; }
        public bool admin { get; set; }
        public Nullable<int> id_nadrzednego { get; set; }
        public string uwagi { get; set; }
        public string uzytkownik { get; set; }
        public System.DateTime last_update { get; set; }
        public bool nieaktywny { get; set; }
        public string login { get; set; }
        public byte[] passwordhash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Badania> Badania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oswiadczenia> Oswiadczenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paszporty> Paszporty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SzkoleniaBHP> SzkoleniaBHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wizy> Wizy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wydania> Wydania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wydania> Wydania1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaproszenia> Zaproszenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zezwolenia> Zezwolenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zatrudnienia> Zatrudnienia { get; set; }
    }
}
