//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opportunity.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Towary()
        {
            this.Przyjecia = new HashSet<Przyjecia>();
            this.Wycofania = new HashSet<Wycofania>();
            this.Wydania = new HashSet<Wydania>();
        }
    
        public int id { get; set; }
        public int id_typu { get; set; }
        public string nazwa { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public string ean { get; set; }
        public string path_zdjecie { get; set; }
        public string path_gwarancja { get; set; }
        public bool premium { get; set; }
        public string status { get; set; }
        public string uwagi { get; set; }
        public string uzytkownik { get; set; }
        public System.DateTime last_update { get; set; }
        public bool nieaktywny { get; set; }
        public Nullable<int> id_marki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przyjecia> Przyjecia { get; set; }
        public virtual Slownik_typy_towarow Slownik_typy_towarow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wycofania> Wycofania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wydania> Wydania { get; set; }
        public virtual Slownik_marki Slownik_marki { get; set; }
    }
}
