//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opportunity.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wydania
    {
        public int id { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Ilosc { get; set; }
        public int id_towaru { get; set; }
        public string nazwa_towaru { get; set; }
        public Nullable<int> id_wydajacego { get; set; }
        public string wydajacy { get; set; }
        public Nullable<int> id_przyjmujacego { get; set; }
        public string przyjmujacy { get; set; }
        public Nullable<System.DateTime> data_potwierdzenia_przyjecia { get; set; }
        public Nullable<System.DateTime> data_potwierdzenia_wydania { get; set; }
    }
}
