//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opportunity.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wydania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wydania()
        {
            this.Potwierdzenia = new HashSet<Potwierdzenia>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_wydajacego { get; set; }
        public Nullable<int> id_przyjmujacego { get; set; }
        public int id_towaru { get; set; }
        public decimal ilosc { get; set; }
        public System.DateTime data { get; set; }
        public string uwagi { get; set; }
        public string uzytkownik { get; set; }
        public System.DateTime last_update { get; set; }
        public bool nieaktywne { get; set; }
        public Nullable<int> wykonano { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Potwierdzenia> Potwierdzenia { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Pracownicy Pracownicy1 { get; set; }
        public virtual Towary Towary { get; set; }
    }
}
